### ISSUE TITLE
Sample bots doesn't work

### ISSUE THREAD

**Issue by a-a-k** [pouladpld/Telegram.Bot.Framework#2]
Are they ok? )

**Comment by poulad** [comment]
I have a problem with my server so bots are down now.
But if you are talking about the code, please check samples(and Wiki) in `games` branch. Due to bugs in `Telegram.Bot` project, I haven't merged that code into `master` yet.

**Comment by poulad** [comment]
@a-a-k Samples are working now.

**Comment by ebbystephen** [comment]
SampleEchoBot is not working. Getting build error.
![sampleechobot](https://user-images.githubusercontent.com/45727164/50040209-27a77d00-0037-11e9-98bd-8e6b6276e86e.PNG)
