### ISSUE TITLE
Telegram.Bot vs Telegram.Bot.Framework

### ISSUE THREAD

**Issue by agat366** [pouladpld/Telegram.Bot.Framework#23]
Hi!

I see there are two similar nuget packages created by you, both for Telegram Bot. They both can target asp.net core, thus it's not clear how are they different and when to use each of those.

Could you clarify on that?

**Comment by MihaZupan** [comment]
Telegram.Bot is the core library for interacting with the bot API. It's a rather simple wrapper over the api.
This framework uses Telegram.Bot to build abstractions over the api that make it easier to build bots.

**Comment by agat366** [comment]
Thanks!
